parameters:
- name: build_action
  displayName: Pipeline Action
  type: string
  default: CI
  values:
    - CI
    - Apply
    - Destroy
    - Test

- name: deploy_location
  displayName: Cloud Region
  type: string
  default: uksouth
  values:
    - uksouth
    - ukwest
    - westeurope
    - northeurope
  
- name: deploy_environment
  displayName: Deploy Environment
  type: string
  default: Sandbox
  values:
    - Sandbox
    - Test
    - Dev
    - Staging
    - Prod

variables:
- name: environment
  value: ${{ parameters.deploy_environment }}
- name: pipelineName
  value: Global-Infrastructure
- name: serviceConnection
  value: hax-automation

# Define build numbering pattern
name: "$(Date:yyyyMMdd-HHmm)-${{ parameters.deploy_location}}-${{ parameters.deploy_environment }}-${{ parameters.build_action }}"


stages:
- stage: Bootstrap
  jobs:
  - job: Bootstrap_Subscription
    steps:
    - template: 'pipeline-steps/bootstrap.yml'
      parameters:
        serviceConnection: {{ variables.serviceConnection }}
        environment: {{ variables.environment }}

