parameters:
- name: build_action
  displayName: Pipeline Action
  type: string
  default: CI
  values:
    - CI
    - Apply
    - Destroy
    - Test

- name: deploy_location
  displayName: Cloud Region
  type: string
  default: uksouth
  values:
    - uksouth
    - ukwest
    - westeurope
    - northeurope
  
- name: deploy_environment
  displayName: Deploy Environment
  type: string
  default: Sandbox
  values:
    - Sandbox
    - Test
    - Dev
    - Staging
    - Prod

variables:
- name: environment
  value: ${{ parameters.deploy_environment }}
- name: pipelineName
  value: Global-Infrastructure

# Define build numbering pattern
name: "${{ parameters.deploy_location}}-${{ parameters.deploy_environment }}-${{ parameters.build_action }}-$(Date:yyyyMMdd:HHmm)"


stages:
- stage: Bootstrap
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Core
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Network
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!


